### ISSUE TITLE
DATA: Upgrade & Migrate `Review`

### ISSUE THREAD

**Issue by ElbekDeveloper** [ElbekDeveloper/CashOverflow#188]
## The Ask 
Once #187 is closed, remove `CompanyName` from review model and add `CompanyId` property as a foreign key and migrate

**Comment by ElbekDeveloper** [comment]
Olim

**Comment by ElbekDeveloper** [comment]
@Khojiakbar07 sizga topshirildi bu ish

**Comment by Khojiakbar07** [comment]
ok , we will done
