### ISSUE TITLE
FOUNDATIONS: Handle Missing Exceptions for `LanguageServiceTests`

### ISSUE THREAD

**Issue by ElbekDeveloper** [ElbekDeveloper/CashOverflow#233]
`DbUpdateConcurrencyException`

 `DbUpdateException`

![image](https://github.com/ElbekDeveloper/CashOverflow/assets/52498074/bc533bd1-13b0-4d22-9a83-e19f1f35d910)

**Comment by ElbekDeveloper** [comment]
Bilol?

**Comment by bilolkobilov** [comment]
WIP
